/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cashier.panels;


import cashier.forms.AddOrderForm;
import cashier.forms.ViewProductForm;
import databaseManager.DatabaseConnectionManager;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Marku
 */
public class CashierOrderTablePanel extends javax.swing.JPanel {
    private AddOrderForm addOrderFormScreen;
    private Connection con;
    private PreparedStatement preparedStatement;
    public ViewProductForm viewProductFormScreen;
    private ResultSet resultSet;
    /**
     * Creates new form CashierOrderTablePanel
     */
    public CashierOrderTablePanel() {
        initComponents();
        connect();
        populateTable();
    }
    
        public void connect() {
        try {
            con = con = DatabaseConnectionManager.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(CashierOrderTablePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void populateTable() {
        try {
            int columnCount;
//            Prepare query to get all active products on the database
            preparedStatement = con.prepareStatement(
                    "SELECT orderId, orders.productId as productId, products.productName as productName, orderQuantity,  totalAmount, orderDate  "
                    + "FROM orders "
                    + "LEFT JOIN products "
                    + "ON orders.productId = products.productId "
                    + "WHERE orders.isVoid = 0;");
//            store results to resultSet
            resultSet = preparedStatement.executeQuery();
//            Fetch metadata to get the information about the table (i.e columnCount, item of each column/row etc.)
            ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
//            Subtract to 1 because isVoid wont be displayed. 
            columnCount = resultSetMetaData.getColumnCount();
            DefaultTableModel defaultTableModel = (DefaultTableModel) tblOrder.getModel();
//           Clear the table to ensure that there are no duplicates
            while (defaultTableModel.getRowCount() > 0) {
                defaultTableModel.removeRow(0);
            }

            while (resultSet.next()) {
//                Used Vector because DefaultTableModel.add(Vector) requires a Vector to add a row
//                but Vectors are slower than ArrayList<> its just in this particular sitaution vector is required.
                Vector row = new Vector();
//                Populate the vector (i.e [1, Pencil , 13, 12, Office Supply])
                for (int start = 1; start <= columnCount; start++) {
                    row.add(resultSet.getString("orderId"));
                    row.add(resultSet.getString("productId"));
                    row.add(resultSet.getString("productName"));
                    row.add(resultSet.getString("orderQuantity"));
                    row.add(resultSet.getString("totalAmount"));
                    row.add(resultSet.getString("orderDate"));
                }
//                Add row to the jTable i.e ([1, Pencil , 13, 12, Office Supply])
                defaultTableModel.addRow(row);

            }

        } catch (SQLException ex) {
            Logger.getLogger(CashierOrderTablePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public boolean isScreenOpened(ArrayList<JFrame> screenArr) {
        for (JFrame screen : screenArr) {
            if (screen != null && screen.isVisible()) {
                screen.setVisible(true);
                screen.toFront();
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtSearchOrder = new javax.swing.JTextField();
        btnSearchProduct = new javax.swing.JButton();
        btnAddOrder = new javax.swing.JButton();
        btnRefreshOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnViewProducts = new javax.swing.JButton();

        jPanel2.setMinimumSize(new java.awt.Dimension(800, 475));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 475));

        btnSearchProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnSearchProduct.setText("Search");
        btnSearchProduct.setPreferredSize(new java.awt.Dimension(60, 30));
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        btnAddOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAddOrder.setText("Add");
        btnAddOrder.setPreferredSize(new java.awt.Dimension(60, 30));
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        btnRefreshOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnRefreshOrder.setText("Refresh");
        btnRefreshOrder.setPreferredSize(new java.awt.Dimension(60, 30));
        btnRefreshOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order Id", "Product Id", "Product Name", "Order Quantity", "Total Amount", "Order Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrder);
        if (tblOrder.getColumnModel().getColumnCount() > 0) {
            tblOrder.getColumnModel().getColumn(0).setMinWidth(65);
            tblOrder.getColumnModel().getColumn(0).setPreferredWidth(65);
            tblOrder.getColumnModel().getColumn(0).setMaxWidth(70);
            tblOrder.getColumnModel().getColumn(1).setMinWidth(65);
            tblOrder.getColumnModel().getColumn(1).setPreferredWidth(65);
            tblOrder.getColumnModel().getColumn(1).setMaxWidth(75);
            tblOrder.getColumnModel().getColumn(3).setMinWidth(100);
            tblOrder.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblOrder.getColumnModel().getColumn(3).setMaxWidth(100);
            tblOrder.getColumnModel().getColumn(4).setMinWidth(100);
            tblOrder.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblOrder.getColumnModel().getColumn(4).setMaxWidth(100);
            tblOrder.getColumnModel().getColumn(5).setMinWidth(120);
            tblOrder.getColumnModel().getColumn(5).setPreferredWidth(120);
            tblOrder.getColumnModel().getColumn(5).setMaxWidth(120);
        }

        btnViewProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnViewProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shoppingCart.png"))); // NOI18N
        btnViewProducts.setText("View Products");
        btnViewProducts.setPreferredSize(new java.awt.Dimension(60, 30));
        btnViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        String searchText = txtSearchOrder.getText().toUpperCase();

        //        Set a tableRowSorter
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>((DefaultTableModel) tblOrder.getModel());
        tblOrder.setRowSorter(rowSorter);
        //      Display all items on the table if search textfield is blank
        if (searchText.trim().length() == 0) {
            rowSorter.setRowFilter(null);
            //      Display filtered Results based on regexFilter
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter(searchText));
        }
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void btnViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsActionPerformed

        if (viewProductFormScreen == null) {
            viewProductFormScreen = new ViewProductForm();
        }
        //        Displays the current deleteOrderForm and send it to the front if an instance already exists
        viewProductFormScreen.setVisible(true);
        viewProductFormScreen.toFront();

    }//GEN-LAST:event_btnViewProductsActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed

        if (addOrderFormScreen == null) {
            addOrderFormScreen = new cashier.forms.AddOrderForm(this);
        }
//        Displays the current deleteOrderForm and send it to the front if an instance already exists
        addOrderFormScreen.setVisible(true);
        addOrderFormScreen.toFront();
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void btnRefreshOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshOrderActionPerformed
        this.populateTable();

    }//GEN-LAST:event_btnRefreshOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnRefreshOrder;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtSearchOrder;
    // End of variables declaration//GEN-END:variables
}
