/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin.panels;

import admin.forms.AddProductForm;
import admin.forms.EditProductForm;
import databaseManager.DatabaseConnectionManager;

import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marku
 */
public class AdminProductTablePanel extends javax.swing.JPanel {
    private AddProductForm addProductFormScreen;
    private EditProductForm editProductFormScreen;
    private Connection con;
    private PreparedStatement preparedStatement;
    private ResultSet resultSet;
    /**
     * Creates new form ProductTablePanel
     */
    public AdminProductTablePanel() {
        initComponents();
        connect();
        populateTable();
    }
    
    //  Connect to the database
    public void connect() {
        try {
            con = DatabaseConnectionManager.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(AdminProductTablePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public void populateTable() {
          try {
            int columnCount;
//            Prepare query to get all active products on the database
            preparedStatement = con.prepareStatement("SELECT * FROM products WHERE isVoid = 0");
//            store results to resultSet
            resultSet = preparedStatement.executeQuery();
//            Fetch metadata to get the information about the table (i.e columnCount, item of each column/row etc.)
            ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
//            Subtract to 1 because isVoid wont be displayed. 
            columnCount = resultSetMetaData.getColumnCount() - 1;
            DefaultTableModel defaultTableModel = (DefaultTableModel) tblProduct.getModel();
//           Clear the table to ensure that there are no duplicates
            while (defaultTableModel.getRowCount() > 0) {
                defaultTableModel.removeRow(0);
            }

            while (resultSet.next()) {
//                Used Vector because DefaultTableModel.add(Vector) requires a Vector to add a row
//                but Vectors are slower than ArrayList<> its just in this particular sitaution vector is required.
                Vector row = new Vector();
//                Populate the vector (i.e [1, Pencil , 13, 12, Office Supply])
                for (int start = 1; start <= columnCount; start++) {
                    row.add(resultSet.getString("productId"));
                    row.add(resultSet.getString("productName"));
                    row.add(resultSet.getString("price"));
                    row.add(resultSet.getString("stockQuantity"));
                    row.add(resultSet.getString("productType"));
                }
//                Add row to the jTable i.e ([1, Pencil , 13, 12, Office Supply])
                defaultTableModel.addRow(row);

            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminProductTablePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
// Check if a screen is currently opened 
    public boolean isScreenOpened(ArrayList<JFrame> screenArr) {
        for (JFrame screen : screenArr) {
            if (screen != null && screen.isVisible()) {
                screen.setVisible(true);
                screen.toFront();
                return true;
            }
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtSearchProduct = new javax.swing.JTextField();
        btnSearchProduct = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnEditProduct = new javax.swing.JButton();
        btnRefreshOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(682, 708));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 475));

        btnSearchProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnSearchProduct.setText("Search");
        btnSearchProduct.setPreferredSize(new java.awt.Dimension(60, 30));
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAddProduct.setText("Add");
        btnAddProduct.setPreferredSize(new java.awt.Dimension(60, 30));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnEditProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnEditProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        btnEditProduct.setText("Edit");
        btnEditProduct.setPreferredSize(new java.awt.Dimension(60, 30));
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        btnRefreshOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnRefreshOrder.setText("Refresh");
        btnRefreshOrder.setPreferredSize(new java.awt.Dimension(60, 30));
        btnRefreshOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Price", "Stock Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProduct.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblProduct);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        String searchText = txtSearchProduct.getText().toUpperCase();
        
//        Set a tableRowSorter
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>((DefaultTableModel) tblProduct.getModel());
        tblProduct.setRowSorter(rowSorter);
//      Display all items on the table if search textfield is blank
        if (searchText.trim().length() == 0) {
            rowSorter.setRowFilter(null);
//      Display filtered Results based on regexFilter
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter(searchText));
        }
        
        
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        //        Create a new instance of EditProductForm if there are no instances
        ArrayList<JFrame> frameArr = new ArrayList<>();
        frameArr.add(addProductFormScreen);
//        Check if there are other Jframe open
        if (isScreenOpened(frameArr) == false) {
            if (editProductFormScreen == null) {
                editProductFormScreen = new EditProductForm(this);
            }
            editProductFormScreen.setVisible(true);
            editProductFormScreen.toFront();
        }
    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        
        ArrayList<JFrame> frameArr = new ArrayList<>();
        frameArr.add(editProductFormScreen);
//        Check if there are any screen opened
        if (isScreenOpened(frameArr) == false) {
            //        Create a new instance of AddProductForm if there are no instances 
            if (addProductFormScreen == null) {
                addProductFormScreen = new AddProductForm(this);
            } 
//        Displays the current AddProductForm and send it to the front if an instance already exists
            addProductFormScreen.setVisible(true);
            addProductFormScreen.toFront();
            
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnRefreshOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshOrderActionPerformed
        this.populateTable();

    }//GEN-LAST:event_btnRefreshOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnRefreshOrder;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtSearchProduct;
    // End of variables declaration//GEN-END:variables
}
