/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme;
import java.awt.CardLayout;

/**
 *
 * @author Marku
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParent = new javax.swing.JPanel();
        adminProductTablePanel = new admin.panels.AdminProductTablePanel();
        adminOrderTablePanel = new admin.panels.AdminOrderTablePanel();
        pnlSidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnViewOrder = new javax.swing.JButton();
        btnViewProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlParent.setBackground(new java.awt.Color(28, 36, 44));
        pnlParent.setForeground(new java.awt.Color(28, 36, 44));
        pnlParent.setPreferredSize(new java.awt.Dimension(800, 500));
        pnlParent.setLayout(new java.awt.CardLayout());
        pnlParent.add(adminProductTablePanel, "card2");
        pnlParent.add(adminOrderTablePanel, "card3");

        getContentPane().add(pnlParent, java.awt.BorderLayout.CENTER);

        pnlSidebar.setBackground(new java.awt.Color(21, 26, 32));
        pnlSidebar.setForeground(new java.awt.Color(21, 26, 32));
        pnlSidebar.setMaximumSize(new java.awt.Dimension(70, 2147483647));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(70, 500));
        pnlSidebar.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(21, 26, 32));

        btnViewOrder.setBackground(new java.awt.Color(21, 26, 32));
        btnViewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/truckx24.png"))); // NOI18N
        btnViewOrder.setBorder(null);
        btnViewOrder.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });

        btnViewProduct.setBackground(new java.awt.Color(21, 26, 32));
        btnViewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shoppingcartx24.png"))); // NOI18N
        btnViewProduct.setBorder(null);
        btnViewProduct.setPreferredSize(new java.awt.Dimension(50, 70));
        btnViewProduct.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnViewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnViewOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSidebar.add(jPanel1, new java.awt.GridBagConstraints());

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) pnlParent.getLayout();
        cardLayout.show(pnlParent, "card3");
        
        
        
    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void btnViewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) pnlParent.getLayout();
        cardLayout.show(pnlParent, "card2");
    }//GEN-LAST:event_btnViewProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
  
           FlatMaterialDeepOceanIJTheme.setup();
    
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private admin.panels.AdminOrderTablePanel adminOrderTablePanel;
    private admin.panels.AdminProductTablePanel adminProductTablePanel;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JButton btnViewProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlSidebar;
    // End of variables declaration//GEN-END:variables
}
